/* ===== EQUIPAMENTO E INVENTÁRIO ===== */

function addWeapon() { const c = document.getElementById('weaponsContainer'), i = wC++, r = document.createElement('div'); r.className = 'equip-row weapons'; r.innerHTML = `<input type="text" data-key="wpn_name_${i}" placeholder="Nome da arma"><input type="text" data-key="wpn_tam_${i}" placeholder="T" style="text-align:center"><input type="text" data-key="wpn_dano_${i}" placeholder="1d10+2"><input type="text" data-key="wpn_integ_${i}" placeholder="0/0"><button class="rm-btn no-print" onclick="this.parentElement.remove();scheduleAutosave()">✕</button>`; c.appendChild(r); r.querySelectorAll('input').forEach(x => x.addEventListener('input', scheduleAutosave)); }

function addArmor() { const c = document.getElementById('armorContainer'), i = aC++, r = document.createElement('div'); r.className = 'equip-row armor'; r.innerHTML = `<input type="text" data-key="arm_name_${i}" placeholder="Vestimenta"><input type="text" data-key="arm_rea_${i}" placeholder="0" style="text-align:center"><input type="text" data-key="arm_bld_${i}" placeholder="0" style="text-align:center"><input type="text" data-key="arm_integ_${i}" placeholder="0/0"><button class="rm-btn no-print" onclick="this.parentElement.remove();scheduleAutosave()">✕</button>`; c.appendChild(r); r.querySelectorAll('input').forEach(x => x.addEventListener('input', scheduleAutosave)); }

function addProjectile() { const c = document.getElementById('projectilesContainer'), i = pC++, r = document.createElement('div'); r.className = 'equip-row projectiles'; r.innerHTML = `<input type="text" data-key="proj_name_${i}" placeholder="Projétil"><input type="text" data-key="proj_dano_${i}" placeholder="1d6"><input type="text" data-key="proj_qtd_${i}" placeholder="0"><button class="rm-btn no-print" onclick="this.parentElement.remove();scheduleAutosave()">✕</button>`; c.appendChild(r); r.querySelectorAll('input').forEach(x => x.addEventListener('input', scheduleAutosave)); }

function addCondition() { const c = document.getElementById('conditionsContainer'), i = cC++, r = document.createElement('div'); r.className = 'equip-row conditions'; r.innerHTML = `<input type="text" data-key="cond_name_${i}" placeholder="Condição"><input type="text" data-key="cond_tipo_${i}" placeholder="Tipo"><input type="text" data-key="cond_desc_${i}" placeholder="Descrição"><input type="text" data-key="cond_tempo_${i}" placeholder="0/0"><button class="rm-btn no-print" onclick="this.parentElement.remove();scheduleAutosave()">✕</button>`; c.appendChild(r); r.querySelectorAll('input').forEach(x => x.addEventListener('input', scheduleAutosave)); }

function addInventoryItem() { const c = document.getElementById('inventoryContainer'), i = iC++, r = document.createElement('div'); r.className = 'inv-row'; r.innerHTML = `<input type="text" data-key="inv_name_${i}" placeholder="Nome do item"><input type="text" data-key="inv_desc_${i}" placeholder="Descrição"><input type="text" data-key="inv_qtd_${i}" placeholder="0" style="text-align:center"><button class="rm-btn no-print" onclick="this.parentElement.remove();scheduleAutosave()">✕</button>`; c.appendChild(r); r.querySelectorAll('input').forEach(x => x.addEventListener('input', scheduleAutosave)); }
